In [1]:
import numpy as np
import pandas as pd

In [2]:
#working with numpy array
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("\n Average number", arr.mean())

[10 20 30 40 50]

 Average number 30.0


In [3]:
#indexing 
print(arr[3])
print(arr[-2])
print(arr[4])
print(arr[-4])

40
40
50
20


In [4]:
#slicing
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])

[20 30 40 50]
[]
[10 20 30 40 50]
[10 20 30 40]
[]
[]


In [5]:
#2D indexing and slicing
arr_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2D[0, 1])
print(arr_2D[1, :])
print(arr_2D[1:2, 2])
print(arr_2D[2, :2])
print(arr_2D[1:3, 0:2])



2
[4 5 6]
[6]
[7 8]
[[4 5]
 [7 8]]


In [6]:
#change to 1D array to 2D array
arr1 = np.arange(1, 13)
reshape = arr1.reshape(4, 3)

print("Original array:", arr1)
print("Reshape array:\n", reshape)

flatten = reshape.flatten()
print("Flatten to 1D:", flatten)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flatten to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
#working with basic mathematics operation
arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array([10, 20, 30, 40, 50])

print(arr_2 + arr_3)
print(arr_2 - arr_3)
print(arr_2 * arr_3)
print(arr_3 / arr_2)

#scaler opertion
print(arr_3**2)
print(arr_3//3)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 100  400  900 1600 2500]
[ 3  6 10 13 16]


In [8]:
#working with matrix using dot(product)
matrix_1 = np.array([
    [1, 2],
    [3, 4]
])

matrix_2 = np.array([
    [5, 6],
    [7, 8]
])

dot = np.dot(matrix_1, matrix_2)
print("Matrix dot product\n", dot)

print("Matrix multiplication\n", matrix_1 * matrix_2)

Matrix dot product
 [[19 22]
 [43 50]]
Matrix multiplication
 [[ 5 12]
 [21 32]]


In [9]:
#work with daily steps analysis using numpy
np.random.seed(42) #reproducibility
days = np.arange(1, 31)
steps = np.random.randint(3456, 12034, size=30)

data = pd.DataFrame({
    "Days": days,
    "Steps": steps
})

data

,Days,Steps
0,1,10726
1,2,4316
2,3,8846
3,4,8647
4,5,9190
5,6,9721
6,7,3922
7,8,7882
8,9,9034
9,10,11778


In [10]:
#basic stats
mean_steps = np.mean(steps)
std_steps = np.std(steps)
print("Average steps:", mean_steps)
print("Standard deviation:", std_steps)
print("Median steps:", np.median(steps))
print("Minimum steps:", np.min(steps))
print("Maximum steps:", np.max(steps))

Average steps: 7500.2
Standard deviation: 2309.770715893679
Median steps: 7946.5
Minimum steps: 3645
Maximum steps: 11778


In [15]:
#goal analysis step exceed 10,000
goal = np.where(steps > 10000)[0] + 1
print(goal)

[ 1 10 13 23]


In [26]:
#weekly analysis (split into 4 weeks)
weeks = np.array_split(steps, 4)
print("Weeks")
print(weeks)
print("Week total")
week_total = [print(week.sum()) for week in weeks]
print("\nWeek average")
week_average = [print(week.mean()) for week in weeks]

Weeks
[array([10726,  4316,  8846,  8647,  9190,  9721,  3922,  7882],
      dtype=int32), array([ 9034, 11778,  5141,  4225, 10405,  5889,  8767,  8507],
      dtype=int32), array([ 9876,  4640,  8011,  6841,  9852,  6014, 11305], dtype=int32), array([5503, 6203, 3645, 6190, 6461, 8114, 5355], dtype=int32)]
Week total
63250
63746
56539
41471

Week average
7906.25
7968.25
8077.0
5924.428571428572


In [32]:
windows = 7
moving_avg = np.convolve(steps, np.ones(windows)/windows, mode="valid")
print("Rolling moving average:", moving_avg[:7])

Rolling moving average: [7909.71428571 7503.42857143 8177.42857143 8596.28571429 8095.42857143
 7386.14285714 7483.85714286]


In [38]:
#Anomaly detection
lower_bound = mean_steps - 2*std_steps
upper_bound = mean_steps + 2*std_steps

print(lower_bound)
print(upper_bound)

anomaly = np.where((steps < lower_bound) | (steps > upper_bound))[0] + 1

print("Anomaly detection low/high:", anomaly)

2880.6585682126415
12119.741431787359
Anomaly detection low/high: []
